@startuml 检验系统表结构
entity bis_blood_cross_list {
  cross_id : 交叉ID
  inspection_id : 检验ID
  in_credit_id : 血液入库库存ID
  method_type_id : 检验方法
  cross_date : 交叉日期
  cross_result1 : 交叉结果1
  cross_result2 : 交叉结果2
  cross_result3 : 交叉结果3
  cross_result4 : 交叉结果4
  cross_person : 交叉人员
  charge : 金额
  workload : 工作量
  charge_date : 收费时间
  charge_person : 收费人员
  charge_state : 收费状态
  cross_state : 交叉状态
  print_flag : 打印状态
  print_number : 打印次数
  check_person : 审核人员
  check_time : 审核时间
  cross_remark : 交叉备注
  cross_amount : 交叉次数
}
entity bis_blood_input {
  in_credit_id : 血液入库库存ID
  blood_type_id : 血液类型id
  blood_bag_id : 血袋号
  in_date : 入库日期
  blood_donor : 献血员
  sex : 性别
  abo_blood_group : ABO血型
  rh_blood_group : RH血型
  blood_amount : 入库血量
  blood_unit : 单位
  blood_charge : 血液费用
  preparation_type : 制备方式
  preparation_date : 制备日期
  atterm_date : 到期日期
  alarm_date : 报警日期
  input_person : 入库人员
  output_person : 出库人员
  output_date : 出库时间
  state_flag : 状态
  scrap_date : 报废日期
  scrap_cause : 报废原因
  scrap_person : 报废人
  charge_state : 收费状态
  charge_date : 收费日期
  charge_person : 收费人员
  inspection_id : 检验单ID
  print_state : 打印状态
  destroy_person : 销毁人员
  destroy_date : 销毁时间
  destroy_position : 销毁地点
  receive_person : 领取人员
  abo_blood_check : 复查ABO血型
  rh_blood_check : 复查RH血型
  inspection_person : 复检者
  check_person : 审核者
  check_time : 审核时间
  blood_source : 血液来源
  in_location : 存储位置
  cross_date : 交叉日期
  remark : 备注
  transport_condition : 运输条件
  external_appearance : 运输外观
  blood_type_code : 产品码
  blood_group_code : 血型码
  blood_atterm_code : 失效日期码
  blood_antibody_check : 抗体复查
  sampling_time : 采集时间
  sampling_person : 采集人员
  charge_num : 收费数量
  receive_time : 接收时间
  lastmodify : 最后修改时间
  blood_id : 血站ID
}
entity bis_blood_packing_class {
  pack_class_id : ID
  blood_type_id : 血液类型id
  pack_class_sort : 排序号
  packing_amount : 包装量
  corresponding_id : 血站对照ID
  cost : 成本
  charge : 收费
  state_flag : 状态
}
entity bis_blood_type {
  sort : 排序号
  blood_name : 血液单位
  blood_unit : 血液名称
  whole_blood_correspond : 全血当量
  blood_adscription : 血液归属
  validity : 保质期(天)
  prompt : 报价提示期限
  if_cross : 是否交叉
  his_id : hid代码
  interdependent_charge : 互助金额
  corresponding_id : 血站代码
  standard_id : 标准ID
  custom_code : 自定义码
  spell_code : 拼音码
  state_flag : 使用状态
  blood_type_id : 血液类型id
}
entity bis_test_method_type {
  type_id : 配血类型ID（3配血法，血液处理法）
  sort : 排序号
  chinese_name : 配血方法名称
  his_id : HIS代码
  charge : 金额
  workload : 工作量
  custom_code : 自定义码
  spell_code : 拼音码
  reside_class : 所属类型
  state_flag : 使用状态
  method_type_id : ID
}
entity his_requisition {
  his_id : 医嘱代码
  requisition_id : 申请单ID
  patient_type : 病人类别（1住院、2门诊、3住院急诊、4门诊急诊、5体检、10质控）
  outpatient_id : 病人ID
  inpatient_id : 就诊唯一号
  charge_type : 收费类型
  patient_name : 病人姓名
  patient_sex : patient_sex
  patient_age : 输入年龄
  patient_nation : 民族代码
  bloodtype_abo : ABO血型
  bloodtype_rh : RH血型
  patient_dept : 申请科室代码
  patient_dept_name : patient_dept_name
  patient_ward : 申请病区代码
  patient_ward_name : 申请病区名称
  patient_bed : 病人床号
  especial_condition : 特殊说明
  inspected_info : 检查信息
  infection : 传染标记
  clinical_diagnoses : 临床诊断
  medical_record : 病例档案
  requisition_dept : 申请科室
  requisition_time : 申请时间
  requisition_person : 申请人员
  execute_dept : 执行科室
  execute_time : 执行时间
  execute_person : 执行人员
  print_dept : 打印时间
  print_time : 打印时间
  print_person : 打印人员
  sample_class : 样本类型
  id : id
  sampling_position : 采样地点
  sampling_dept : 采样科室
  sampling_time : 采样时间
  sampling_person : 采样人员
  receive_dept : 接收科室
  receive_time : 接收时间
  receive_person : 接收人员
  charge_item_id : 项目代码
  charge_name : 收费名称
  charge : 收费金额
  charge_state : 收费状态
  charge_time : 收费时间
  charge_person : 收费人员
  requisition_state : 申请单状态
  remark : 备注
  requisition_from : 申请单来源
  return_person : 退回人员
  return_cause : 退回原因
  return_time : 退回时间
  Document_type : 证件类型
  outpatinet_times : 就诊次数
  delivery_person : 送达人员
  delivery_time : 送达时间
  send_person : 送达人员
  send_time : 送达时间
  Residential_address : 家庭地址
  Residential_address2 : 现居住地址
  mobile_no : 手机号码
}
entity lis_base_data {
  base_data_id : 基础数据ID
  class_id : 字典类型
  base_data_sort : 排序号
  chinese_name : 中文名称
  english_name : 英文名称
  his_id : HIS代码
  standart_id : 标准代码
  custom_code : 自定义码
  spell_code : 拼音码
  stroke_code : 五笔码
  state_flag : 状态
  custom01 : 分类1
  custom02 : 分类2
  custom03 : 分类3
  custom04 : 统计分类(检验科室)
}
entity lis_base_data_group {
  spell_code : 拼音码
  stroke_code : 五笔码
  standard_name : 标准名称
  group_id : 检验分组ID
  custom_code : 自定义码
  base_data_sort : 排序号
  base_data_id : 基础数据ID
}
entity lis_change_log {
  serial_no : 日志ID
  module_type : 操作模块类型
  change_type : 日志类型
  change_class : 操作类型
  inspection_id : 检验单ID
  change_content : 操作内容
  change_cause : 操作原因
  change_person : 操作人员
  change_time : 操作时间
  change_place : 操作电脑
  remark : 备注信息
}
entity lis_change_log_micro {
  id : 日志ID
  change_id : 诊疗项目代码
  change_soft : 修改模块
  change_person : 修改人员
  change_time : 修改时间
  change_where : 修改条件
  change_content : 修改内容
}
entity lis_charge_item {
  charge_item_id : 诊疗项目ID
  chinese_name : 诊疗项目名称
  chinese_name_short : 诊疗项目简称
  english_name : 诊疗项目英文名称
  his_id : HIS代码
  medicare_id : 医保代码（对应惠桥代码）
  standart_id : 标准代码（返回给体检系统代码）
  barcode_seq : 条码规则序号
  charge_item_sort : 诊疗项目分类（免疫、生化、体液）
  charge : 诊疗项目金额（与HIS对应）
  sample_class : 默认标本种类
  patient_type : 项目开展类型
  sampling_request : 采样要求
  sampling_time : 允许采样时间
  sampling_place : 采样地点
  report_time : 报告时间
  report_place : 报告地点
  report_time_sort : 报告时间序号
  inspection_time : 开展时间（默认每天都开展）
  workload : 工作量
  test_item_count : 项目数量
  unite_flag : 合并标记（共管标识）
  custom_code : 自定义码
  spell_code : 拼音码
  stroke_code : 五笔码
  used_flag : 是否常用：1是，空不是
  state_flag : 使用状态：1使用，0禁用
  number_priority : 编号规则
  save_term : 标本保留天数
  group_id : 所属检验分组
  tjxmbh : 体检代码（未使用）
  number_print : 检验条码打印份数
}
entity lis_charge_item_charge {
  charge_class : 收费类型
  his_id : HIS代码
  charge_name : 收费名称
  charge : 收费金额
}
entity lis_charge_item_inspectiontime {
  time_type : 超时类型
  patient_type : 病人类型
  id : 主键
  charge_item_id : 诊疗项目ID
  inspection_time : 检验时间（超时提醒）
}
entity lis_charge_item_reporttime {
  charge_item_id : 诊疗项目ID
  from_time : 开始时间
  to_time : 结束时间
  week_date : 星期几出报告
  report_time : 报告时间
  from_date : 开始日期
  to_date : 结束日期
  id : 主键
}
entity lis_comm_instrument {
  instrument_id : 仪器代码
  instrument_key_date : 注册时间
  instrument_type : 仪器类型
  interface_name : 接口程序
  interface_type : 通讯方式
  instrument_name : 仪器名称
  instrument_commport : 使用端口号
  instrument_key : key
}
entity lis_inspection_group {
  group_id : 分组ID
  group_code : 分组代码
  group_sort : 排序号
  group_name : 分组名称
  inspection_dept : 检验科室
  group_class : 分组类型
  lis_id : 老系统代码
  test_item_append : 项目显示格式
  start_no : 起诉样本号
  start_focus : 开始焦点
  result_review : 回顾条件设置
  same_group : 同类分组
  graph_format : 结果图形类型
  graph_switch_file : 对应老系统仪器
  state_flag : 状态
  default_result : 默认结果
}
entity lis_inspection_report {
  inspection_id : 检验单ID
  report_id : 报告序号（页码）
  report_format : 报告单模板
  report_file : 报告单文件
  report_title : 报告单抬头
  create_time : 创建时间
  create_person : 创建人员
  inspection_class : 检验类型
}
entity lis_inspection_result {
  inspection_id : 检验单ID
  test_item_id : 项目代码
  group_id : 分组ID
  inspection_date : 检验日期
  inspection_time : 检验时间
  sample_number : 样本编号
  test_item_sort : 排序号
  english_name : 英文名称
  chinese_name : 中文名称
  original_result : 原始结果
  quantitative_result : 结果
  qualitative_result : 异常标识
  test_item_reference : 参考范围
  test_item_unit : 项目单位
  test_item_charge : 收费价格
  workload : 工作量
  test_count : 项目数
  test_order : 测试代码
  inspection_instrument : 检验仪器
  inspection_person : 检验人员
  inspection_position : 检验位置
  report_id : 报告序号
  col_position : 报告位置
  print_id : 打印页码
  remark : 备注
  check_person : 审核人员
  check_time : 审核时间
  result_type : 结果类型
  test_method : 检测方法
  read_doctor : 阅读医生
}
entity lis_inspection_result_micro {
  inspection_id : 检验单ID
  group_id : 分组ID
  inspection_date : 检验日期
  inspection_time : 检验时间
  sample_number : 样本编号
  result_type : 结果类型，ya阳性,tp涂片，py拼音
  result_method : 检测方法
  micro_data_id : 微生物代码
  micro_data_id_sort : 微生物类型排序
  micro_data_id_name : 微生物名称
  micro_data_id_result1 : 菌落技术
  micra_data_id2 : 抗生素代码
  micra_data_id2_sort : 抗生素类型排序
  micro_data_id2_name : 抗生素名称（药敏）
  micro_data_id2_result1 : 药敏定量结果
  micro_data_id2_result2 : 药敏定性结果
  micro_data_id2_range : 抗生素（药敏）参考值
  inspection_instrument : 药敏检测仪器
  inspection_position : 检验位置
  inspection_person : 检验人员
  remark : 备注
  esbl : esbl
  read_doctor : 临床阅读医生
  report_id : 打印序号
}
entity lis_inspection_sample {
  inspection_id : 检验单ID
  group_id : 分组ID
  inspection_date : 检验日期（样本编号时自动生成）
  inspection_time : 检验时间（样本编号时自动生成）
  sample_number : 样本编号
  requisition_id : 申请单ID
  patient_type : 病人类别（1住院、2门诊、3住院急诊、4门诊急诊、5体检、10质控）
  outpatient_id : 病人ID
  inpatient_id : 就诊唯一号
  invoice_id : 发票号码
  charge_type : 收费类型
  patient_name : 病人姓名
  patient_sex : 病人性别（1男，2女，3不详）
  age_type : 年龄类型
  age_input : 输入年龄
  age_save : 保存年龄（换算分钟）
  patient_nation : 民族代码
  patient_nation_name : 民族名称
  bloodtype_abo : ABO血型
  bloodtype_rh : RH血型
  patient_dept : 申请科室代码
  patient_dept_name : 申请科室名称
  patient_ward : 申请病区代码
  patient_ward_name : 申请病区名称
  patient_bed : 病人床号
  especial_condition : 特殊说明
  clinical_diagnoses : 临床诊断代码
  clinical_diagnoses_name : 临床诊断名称
  sample_class : 标本种类代码
  sample_class_name : 标本种类名称
  infect_status : 传染标记
  sample_status : 标本形状代码
  sample_status_name : 标本形状名称
  sampling_position : 取样位置
  sampling_position_name : 取样位置
  test_order : 检验目的代码
  test_order_name : 检验目的名称
  sample_charge : 样本金额
  item_count : 样本数量
  workload : 工作量
  sampling_time : 采样时间
  sampling_person : 采样人员
  requisition_time : 开单时间
  requisition_person : 开单人员
  deliver_hospital : 送检单位
  incept_time : 接收时间
  incept_person : 接收人员
  input_person : 录入人员
  input_time : 录入时间
  inspection_person : 检验人员
  check_person : 审核人员
  check_time : 审核时间
  print_person : 打印人员
  print_time : 打印时间
  print_count : 打印次数
  expert_rule : 专家规则
  id_card : 身份证号
  charge_state : 收费状态
  inspection_state : 检验状态
  rerun_state : 复查状态
  read_state : 临床阅读状态
  remark : 备注代码
  remark_name : 备注名称
  confirm_time : 批准时间
  confirm_person : 批准人员
  instrument : 仪器
  mobileno : 手机号码
  send_state : 发送状态
  send_date : 发送时间
  patient_birthday : 出生日期
  blood_mode : 血缘关系
  read_doctor : 阅读医生
  read_time : 阅读时间
  check_temp_time : 初步报告时间
  InspectionTime : 检验审核时间
  result_incept_state : 结果接收状态
  blood_output_print_time : 血液出库打印时间
  receive_person : 接收人员
  police_state : 危急值提醒状态
  readed_state : lis42报告单是否已经看过
  police_time : 下次提醒时间
  police_person : 未指定检验人员时，检验提示信息不再提示人员序号，用“,”分隔
}
entity lis_inspection_sample_charge {
  sample_charge_id : 收费ID
  requisition_id : 申请单ID
  inspection_id : 检验单ID
  charge_item_id : 收费项目ID
  chinese_name_short : 项目简称
  amount : 项目数
  charge : 收费金额
  workload : 工作量
  charge_person : 收费人员
  charge_time : 收费时间
  charge_postion : 计算机名称
  charge_state : 收费状态
  charge_type : 收费类型
  his_id : HIS代码
  charge_num : 备用字段
}
entity lis_inspection_sample_explain {
  inspection_id : 检验单ID
  explain_id : 解释ID，跟lis_base_data关联
  explain : 结果解释
}
entity lis_inspection_sample_graph {
  inspection_id : 检验单ID
  inspection_date : 检验日期
  inspection_instrument : 检验仪器
  graph_format : 图片格式
  remark : 备注
}
entity lis_test_item {
  test_item_id : 项目ID
  test_item_code : 项目代码
  test_item_sort : 排序号
  chinese_name : 中文名称
  chinese_short_name : 中文简称
  english_name : 英文名称
  english_short_name : 英文简称
  standard_id : 标准代码
  his_id : HIS代码（HIS关联码）
  lis_id : 老系统代码
  medical_id : 医保代码
  test_item_type : 项目类型:计算类、非计算类
  test_item_class : 项目分类（按检验科室分类）
  expressions : 计算公式
  test_item_charge : 收费金额
  test_item_unit : 单位
  test_item_precision : 结果精度（小数点保留）
  modulus : 项目系数
  correlative_equation : 相关方程
  display_type : 显示类型
  regulation_file : 操作规程文件
  repository_file : 知识库文件
  test_method : 检验方法
  reagent_dosage : 试剂用量
  custom_code : 自定义码
  spell_code : 拼音码
  stroke_code : 五笔码
  state_flag : 状态
  standard_name : 标准名称
  pes_id : 体检关联码
}
entity lis_test_item_combination {
  serial_no : 排序
  combination_id : 组合ID
  combination_sort : 排序号
  sample_class : 标本类型代码
  test_item_id : 项目ID
  base_data_sort : 项目排序
  default_result : 默认结果
  combination_name : 组合名称
  standart_id : 标准ID
  custom_code : 自定义码
  spell_code : 拼音码
  stroke_code : 五笔码
  state_flag : 状态
}
entity lis_test_item_group {
  group_id : 分组ID
  test_item_id : 项目ID
  test_item_sort : 排序
  test_item_type : 项目类型
  expressions : 计算公式
  modulus : 项目系数
  custom_code : 自定义码
  spell_code : 拼音码
  stroke_code : 五笔码
  flag : 状态
  sample_class : 标本类型代码
}
entity sys_user {
  user_no : 用户id
  logid : 登录名
  username : 用户名称
  password : 密码
  his_id : HIS代码
  ime : 默认输入法
  dept_code : 所属科室
  tech_post : 职务
  select_group : 可操作分组
  state_flag : 状态
  material_dept : 物质部门
  mobileno : 手机号码
  ime_chinese_name : 输入法类型
  tmis_id : 血站中心ID
  id_card : 身份证号码
}
@enduml